version: "3.5"
services:
  nginx:
    image: m2162003/nginx:latest
    ports:
      - 80:80
    depends_on:
      - springboot
    restart: "unless-stopped"
  springboot:
    image: m2162003/springboot:latest
    ports:
      - 8080:8080
    restart: "unless-stopped"
