version: "3.5"

services:
  # django:
  #   build:
  #     context: . #도커 빌드를 실행할 경로
  #     dockerfile: ./emart2-server/Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./:/app/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: ./emart2-client/Dockerfile
    volumes:
      - ./:/app/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    # depends_on: -django
