name: my workflow # Workflow 이름
on: # Event 감지
  push:
    branches:
      - master

jobs: # Job 설정
  build: # Job ID
    runs-on: ubuntu-18.04 # Job 가상환경 인스턴스
    steps: # Steps
      - name: checkout source code # Step 이름
        uses: actions/checkout@master # Uses를 통한 외부 설정 가져오기: 자신의 레포지토리 소스 받아오기

      # - name: Cache node modules
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      #     restore-key: |
      #       ${{ runner.OS }}-build-
      #       ${{ runner.OS }}-

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
